specVersion: 1.0.0
name: xcm-index-test
version: 0.0.4
runner:
  node:
    name: '@subql/node'
    version: '>=1.0.0'
  query:
    name: '@subql/query'
    version: '*'
description: "Index xcm reserve transfers"
repository: 'https://github.com/AstarNetwork/astar-subql-xcm'
schema:
  file: ./schema.graphql
network:
  chainId: '0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6'
  endpoint: 'wss://astar.api.onfinality.io/public-ws#/'
  dictionary: 'https://api.subquery.network/sq/subquery/astar-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1 #xcm start
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEventXcm
          kind: substrate/EventHandler
          filter:
            module: dmpqueue
            method: ExecutedDownward
        # - handler: handleBalancesTransfer
        #   kind: substrate/EventHandler
        #   filter:
        #     module: balances
        #     method: Transfer
